run:
  tests: true
  skip-dirs:
    - admin/generated
    - internal/testserver/generated
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
linters-settings:
  goconst:
    min-occurrences: 5
  golint:
    min-confidence: 0.1
  funlen:
    lines: 99
    statements: 60
linters:
  enable-all: true
  disable:
    - containedctx
    - gocognit
    - gochecknoinits
    - gofumpt
    - errcheck
    - lll
    - wsl
    - gomnd
    - testpackage
    - exhaustivestruct
    - paralleltest
    - cyclop
    - forcetypeassert
    - tagliatelle
    - varnamelen
    - wrapcheck
    - goerr113
    - gochecknoglobals

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - ireturn
        - noctx
        - dupl
        - funlen
        - errcheck
    - path: admin/schema.resolvers\.go
      linters:
        - ireturn
    - path: internal/testserver/schema.resolvers\.go
      linters:
        - ireturn