# -- The number of replicas (pods) to launch
replicaCount: 1

image:
  # -- Name of the image repository to pull the container image from.
  repository: gboxproxy/gbox
  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for updating already existing images on a node.
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""
# -- Reference to one or more secrets to be used when [pulling images](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) (from private registries).
imagePullSecrets: []
# -- A name in place of the chart name for `app:` labels.
nameOverride: ""
# -- A name to substitute for the full names of resources.
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations to be added to pods.
podAnnotations: {}

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) for details.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
  type: ClusterIP
  # -- Service port.
  port: 80

ingress:
  # -- Enable [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).
  enabled: false
  # -- Ingress [class name](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class).
  className: ""
  # -- Annotations to be added to the ingress.
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host configuration.
  # @default -- See [values.yaml](values.yaml).
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- Ingress TLS configuration.
  # @default -- See [values.yaml](values.yaml).
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Container resource [requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources) for details.
# @default -- No requests or limits.
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Autoscaling by resources
# @default -- Disabled by default.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- [Node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) configuration.
nodeSelector: {}

# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for node taints.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
tolerations: []

# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) configuration.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
affinity: {}

# -- Caddy [global directives](https://caddyserver.com/docs/caddyfile/options).
globalDirectives: ''

# -- Your upstream GraphQL server url.
upstream: ""

# -- Reverse proxy [directives](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy).
reverseProxyDirectives: ""

# -- Interval times to introspect upstream schema definition.
fetchSchemaInterval: 10m

# -- Whether disable playgrounds or not.
disabledPlaygrounds: false

# -- Whether disable introspection queries or not.
disabledIntrospection: false

complexity:
  # -- Whether enable filter query complexity or not.
  enabled: true

  # -- Max query depth.
  maxDepth: 15

  # -- The maximum number of Nodes a query may return.
  nodeCountLimit: 60

  # -- The maximum number of Node requests that might be needed to execute the query.
  maxComplexity: 60

caching:
  # -- Whether enable caching or not.
  enabled: true

  # -- By default, this chart use Redis to storing cached data, if you want to use your external Redis server, remember to disable internal Redis sub-chart.
  # @default -- See [values.yaml](values.yaml).
  storeDsn: '{{ printf "redis://%s@%s-redis-master.%s.svc.cluster.local:6379" .Values.redis.auth.password .Release.Name .Release.Namespace }}'

  # -- Caching rules configuration.
  # @default -- Will cache all query results, see [values.yaml](values.yaml).
  rules: |
    default {
      max_age 30m
      swr 30m
    }

  # -- Caching varies configuration.
  varies: ''

  # -- Specific type keys configuration, by default `id` is key of all types.
  typeKeys: ''

  # -- Whether auto invalidate cached data through mutation results or not.
  autoInvalidateCache: 'true'

  # -- Whether add debug headers to query operations responses or not.
  debugHeaders: 'false'

# -- GBox extra directives, useful in cases you may want to add CORS config and/or http headers when fetch schema from upstream.
extraDirectives: ''

# -- Admin auth configuration.
adminAuth:
  # -- Whether enable basic auth when interact with GraphQL admin endpoint.
  enabled: true

  # -- Basic auth username.
  username: 'gbox'

  # -- Basic auth password.
  # @default -- "gbox"
  password: ''

# Redis sub-chart configuration
redis:
  # -- Whether enable Redis sub-chart or not.
  enabled: true

  # -- Set Redis architecture standalone or replication.
  architecture: standalone

  auth:
    password: '!ChangeMe!'

# -- Prometheus metric endpoint configuration
metrics:
  # -- Whether enable Prometheus metric endpoint or not
  enabled: true

  # -- Url path of metric endpoint.
  path: /metrics