apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "gbox.fullname" .  | quote }}
  labels:
    {{- include "gbox.labels" . | nindent 4 }}
data:
  GBOX_STORE_DSN: {{ tpl .Values.caching.storeDsn . | b64enc | quote }}
  GBOX_ADMIN_USERNAME: {{ .Values.adminAuth.username | b64enc | quote }}
  {{- if ne .Values.adminAuth.password "" }}
  GBOX_ADMIN_PASSWORD: {{ .Values.adminAuth.password | b64enc | quote }}
  {{- end }}