// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookTest struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}

type UserTest struct {
	ID    int         `json:"id"`
	Name  string      `json:"name"`
	Books []*BookTest `json:"books"`
}
