name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git fetch --prune --unshallow

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: sigstore/cosign-installer@main

      - uses: docker/login-action@v1
        with:
          username: gboxproxy
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}