name: Lint and Test

on:
  push:
  pull_request:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - run: go get

    - run: go test -race -covermode atomic -coverprofile=coverage.txt -coverpkg=github.com/gbox-proxy/gbox,github.com/gbox-proxy/gbox/admin ./...

    - uses: codecov/codecov-action@v3
      with:
        files: coverage.txt
